### PR TITLE
Support extra bundles with modules inside Array(N).concat([])

### LINKED ISSUE #29: Could't analyze webpack bundle
#### Issue description

I am getting this message in the end of the webpack emitts:

    TypeError: Cannot read property 'raw' of undefined Could't find any javascript bundles in provided stats file

#### Technical info
* Webpack Bundle Analyzer version: 2.1.1
* Webpack version: 2.1.0-beta.27
* Node.js version:  v7.2.0
* npm/yarn version: 3.10.5/0.17.9
* OS: Windows 10

#### Debug info
How do you use this module?

Plugin

If plugin, what options were provided? 

None

What other Webpack plugins were used?

    new webpack.LoaderOptionsPlugin({
        options: { worker: { output: { filename: "build/worker.js" } } } }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NamedModulesPlugin(),
    new BundleAnalyzerPlugin()

[stats.zip](https://github.com/th0r/webpack-bundle-analyzer/files/616864/stats.zip)

### PR DESCRIPTION
**Pull request by valscion**
Normally, a chunk starts with something like this:

```js
webpackJsonp_adhaghasd([0,2],[ /* modules here */ ])
```

..or like this:

```js
!function(e){/* webpack bootstrap */}([ /* modules here */])
```

But at least in @matteoantoci's case in https://github.com/th0r/webpack-bundle-analyzer/issues/29#issuecomment-276680137, the troublesome chunk starts like this:

```js
webpackJsonplmn_ui_obe__name_Init([0],Array(104).concat([ /* modules here */]))
```

This case was not handled by the utility parsing the module object back from the compiled source using AST parser, [`parseUtils.js`](https://github.com/th0r/webpack-bundle-analyzer/blob/v2.2.0/src/parseUtils.js)

That module template comes from this line in the webpack source code: https://github.com/webpack/webpack/blob/v1.14.0/lib/Template.js#L91

It seems like this is some sort of an optimization inside webpack that allows the modules to be listed in chunks without having to specify hundreds of "empty" elements before.

This PR should hopefully fix #29 with a proper solution (unlike the quickfix done in #42).

**I'm asking all that had the `TypeError` over at #29 to test this out!**

Check out [CONTRIBUTING.md](https://github.com/th0r/webpack-bundle-analyzer/blob/master/CONTRIBUTING.md) on how to test-drive a development version of this plugin.

Just run it from my fork instead:

```
git clone git://github.com/valscion/webpack-bundle-analyzer.git
git checkout support-array-concat-bundles
```

Confirmed to work:

- [x] @matteoantoci https://github.com/th0r/webpack-bundle-analyzer/issues/29#issuecomment-277523357
- [x] @Koslun https://github.com/th0r/webpack-bundle-analyzer/issues/29#issuecomment-277669582
- [ ] @jovinbm 
- [x] @InSuperposition https://github.com/th0r/webpack-bundle-analyzer/issues/29#issuecomment-277892333
- [x] @frankleng 
- [ ] @christianalfoni 
- [ ] @eshion 
- [x] @unsafecode 
- [ ] @drcmda

### CODE REVIEW

**Comment by loris** [comment]
Confirm to work for me too (was having the error since migrating to webpack2 with code splitting and use of commonschunkplugin)

**Comment by frankleng** [comment]
@valscion thanks for the fix. worked for me!

**Comment by th0r** [comment]
Thanks a lot @valscion! Merged.

**Comment by th0r** [comment]
Published in `v2.2.2`

**Comment by jharris4** [comment]
Thanks @valscion for making the PR and @th0r for publishing the new version.

Unfortunately it looks like the lib directory didn't get updated for version 2.2.2 on npm for some reason :-(

https://github.com/th0r/webpack-bundle-analyzer/issues/46

**Comment by th0r** [comment]
Sorry about that, fixed in `v2.2.3`

**Comment by christianalfoni** [comment]
Hi there!

Sorry for my late reply, been home sick a few days.

I am sorry to say it did not work on our project. 

```
Couldn't parse bundle asset "/62a7049a30026325725d.js".
Analyzer will use module sizes from stats file.
```

Versions:

```
webpack 2.2.1
webpack-bundle-analyzer 2.2.3
```

**Comment by valscion** [comment]
That seems to be a separate problem, @christianalfoni. Care to open an issue with more details? Could you maybe post some 500 first and 10 last chars of your bundled files + `stats.json` file to the new issue?

**Comment by christianalfoni** [comment]
@valscion Eyh, what do you know, now it works. Not sure what was changed here. We did a pretty huge refactor on our project though, but also the fact thatI changed some webpack config as well made have affected it. Anyways, it works :)

**Comment by valscion** [comment]
Ok great to hear! :smile:

**Comment by ruiaraujo** [comment]
@valscion I still getting the error with webpack 2.2.1
webpack-bundle-analyzer 2.3.0.

Do you want the bundled files to take a look?

**Comment by valscion** [comment]
Yes please, and please open a new issue :)

**Pull request merged**
