### PR TITLE
Ignore multi entry modules

### PR DESCRIPTION
**Pull request by bsuh**
https://github.com/th0r/webpack-bundle-analyzer/issues/87

Using an array of files for your entry point results in a module with a name beginning with "multi " and a list of paths. Using the string processing of splitting by `/` results in a very deeply nested tree, because the module name contains multiple paths.

"multi ./src2/a/a.js ./src2/a/a/a.js ./src2/a/a/a/a.js ./src2/a/a/a/a/a.js ./src2/a/a/a/a/a/a.js ./src2/a/a/a/a/a/a/a.js ./src2/a/a/a/a/a/a/a/a.js ./src2/a/a/a/a/a/a/a/a/a.js ./src2/a/a/a/a/a/a/a/a/a/a.js ./src2/a/a/a/a/a/a/a/a/a/a/a.js ./src2/b/b.js ./src2/b/b/b.js ./src2/b/b/b/b.js ./src2/b/b/b/b/b.js ./src2/b/b/b/b/b/b.js ./src2/b/b/b/b/b/b/b.js ./src2/b/b/b/b/b/b/b/b.js ./src2/b/b/b/b/b/b/b/b/b.js ./src2/b/b/b/b/b/b/b/b/b/b.js ./src2/b/b/b/b/b/b/b/b/b/b/b.js ./src2/c/c.js ./src2/c/c/c.js ./src2/c/c/c/c.js ./src2/c/c/c/c/c.js ./src2/c/c/c/c/c/c.js ./src2/c/c/c/c/c/c/c.js ./src2/c/c/c/c/c/c/c/c.js ./src2/c/c/c/c/c/c/c/c/c.js ./src2/c/c/c/c/c/c/c/c/c/c.js ./src2/c/c/c/c/c/c/c/c/c/c/c.js ./src2/d/d.js ./src2/d/d/d.js ./src2/d/d/d/d.js ./src2/d/d/d/d/d.js ./src2/d/d/d/d/d/d.js ./src2/d/d/d/d/d/d/d.js ./src2/d/d/d/d/d/d/d/d.js ./src2/d/d/d/d/d/d/d/d/d.js ./src2/d/d/d/d/d/d/d/d/d/d.js ./src2/d/d/d/d/d/d/d/d/d/d/d.js ./src2/e/e.js ./src2/e/e/e.js ./src2/e/e/e/e.js ./src2/e/e/e/e/e.js ./src2/e/e/e/e/e/e.js ./src2/e/e/e/e/e/e/e.js ./src2/e/e/e/e/e/e/e/e.js ./src2/e/e/e/e/e/e/e/e/e.js ./src2/e/e/e/e/e/e/e/e/e/e.js ./src2/e/e/e/e/e/e/e/e/e/e/e.js ./src2/f/f.js ./src2/f/f/f.js ./src2/f/f/f/f.js ./src2/f/f/f/f/f.js ./src2/f/f/f/f/f/f.js ./src2/f/f/f/f/f/f/f.js ./src2/f/f/f/f/f/f/f/f.js ./src2/f/f/f/f/f/f/f/f/f.js ./src2/f/f/f/f/f/f/f/f/f/f.js ./src2/f/f/f/f/f/f/f/f/f/f/f.js ./src2/g/g.js ./src2/g/g/g.js ./src2/g/g/g/g.js ./src2/g/g/g/g/g.js ./src2/g/g/g/g/g/g.js ./src2/g/g/g/g/g/g/g.js ./src2/g/g/g/g/g/g/g/g.js ./src2/g/g/g/g/g/g/g/g/g.js ./src2/g/g/g/g/g/g/g/g/g/g.js ./src2/g/g/g/g/g/g/g/g/g/g/g.js ./src2/h/h.js ./src2/h/h/h.js ./src2/h/h/h/h.js ./src2/h/h/h/h/h.js ./src2/h/h/h/h/h/h.js ./src2/h/h/h/h/h/h/h.js ./src2/h/h/h/h/h/h/h/h.js ./src2/h/h/h/h/h/h/h/h/h.js ./src2/h/h/h/h/h/h/h/h/h/h.js ./src2/h/h/h/h/h/h/h/h/h/h/h.js ./src2/i/i.js ./src2/i/i/i.js ./src2/i/i/i/i.js ./src2/i/i/i/i/i.js ./src2/i/i/i/i/i/i.js ./src2/i/i/i/i/i/i/i.js ./src2/i/i/i/i/i/i/i/i.js ./src2/i/i/i/i/i/i/i/i/i.js ./src2/i/i/i/i/i/i/i/i/i/i.js ./src2/i/i/i/i/i/i/i/i/i/i/i.js ./src2/j/j.js ./src2/j/j/j.js ./src2/j/j/j/j.js ./src2/j/j/j/j/j.js ./src2/j/j/j/j/j/j.js ./src2/j/j/j/j/j/j/j.js ./src2/j/j/j/j/j/j/j/j.js ./src2/j/j/j/j/j/j/j/j/j.js ./src2/j/j/j/j/j/j/j/j/j/j.js ./src2/j/j/j/j/j/j/j/j/j/j/j.js ./src2/k/k.js ./src2/k/k/k.js ./src2/k/k/k/k.js ./src2/k/k/k/k/k.js ./src2/k/k/k/k/k/k.js ./src2/k/k/k/k/k/k/k.js ./src2/k/k/k/k/k/k/k/k.js ./src2/k/k/k/k/k/k/k/k/k.js ./src2/k/k/k/k/k/k/k/k/k/k.js ./src2/k/k/k/k/k/k/k/k/k/k/k.js ./src2/l/l.js ./src2/l/l/l.js ./src2/l/l/l/l.js ./src2/l/l/l/l/l.js ./src2/l/l/l/l/l/l.js ./src2/l/l/l/l/l/l/l.js ./src2/l/l/l/l/l/l/l/l.js ./src2/l/l/l/l/l/l/l/l/l.js ./src2/l/l/l/l/l/l/l/l/l/l.js ./src2/l/l/l/l/l/l/l/l/l/l/l.js ./src2/m/m.js ./src2/m/m/m.js ./src2/m/m/m/m.js ./src2/m/m/m/m/m.js ./src2/m/m/m/m/m/m.js ./src2/m/m/m/m/m/m/m.js ./src2/m/m/m/m/m/m/m/m.js ./src2/m/m/m/m/m/m/m/m/m.js ./src2/m/m/m/m/m/m/m/m/m/m.js ./src2/m/m/m/m/m/m/m/m/m/m/m.js ./src2/n/n.js ./src2/n/n/n.js ./src2/n/n/n/n.js ./src2/n/n/n/n/n.js ./src2/n/n/n/n/n/n.js ./src2/n/n/n/n/n/n/n.js ./src2/n/n/n/n/n/n/n/n.js ./src2/n/n/n/n/n/n/n/n/n.js ./src2/n/n/n/n/n/n/n/n/n/n.js ./src2/n/n/n/n/n/n/n/n/n/n/n.js ./src2/o/o.js ./src2/o/o/o.js ./src2/o/o/o/o.js ./src2/o/o/o/o/o.js ./src2/o/o/o/o/o/o.js ./src2/o/o/o/o/o/o/o.js ./src2/o/o/o/o/o/o/o/o.js ./src2/o/o/o/o/o/o/o/o/o.js ./src2/o/o/o/o/o/o/o/o/o/o.js ./src2/o/o/o/o/o/o/o/o/o/o/o.js ./src2/p/p.js ./src2/p/p/p.js ./src2/p/p/p/p.js ./src2/p/p/p/p/p.js ./src2/p/p/p/p/p/p.js ./src2/p/p/p/p/p/p/p.js ./src2/p/p/p/p/p/p/p/p.js ./src2/p/p/p/p/p/p/p/p/p.js ./src2/p/p/p/p/p/p/p/p/p/p.js ./src2/p/p/p/p/p/p/p/p/p/p/p.js ./src2/q/q.js ./src2/q/q/q.js ./src2/q/q/q/q.js ./src2/q/q/q/q/q.js ./src2/q/q/q/q/q/q.js ./src2/q/q/q/q/q/q/q.js ./src2/q/q/q/q/q/q/q/q.js ./src2/q/q/q/q/q/q/q/q/q.js ./src2/q/q/q/q/q/q/q/q/q/q.js ./src2/q/q/q/q/q/q/q/q/q/q/q.js ./src2/r/r.js ./src2/r/r/r.js ./src2/r/r/r/r.js ./src2/r/r/r/r/r.js ./src2/r/r/r/r/r/r.js ./src2/r/r/r/r/r/r/r.js ./src2/r/r/r/r/r/r/r/r.js ./src2/r/r/r/r/r/r/r/r/r.js ./src2/r/r/r/r/r/r/r/r/r/r.js ./src2/r/r/r/r/r/r/r/r/r/r/r.js ./src2/s/s.js ./src2/s/s/s.js ./src2/s/s/s/s.js ./src2/s/s/s/s/s.js ./src2/s/s/s/s/s/s.js ./src2/s/s/s/s/s/s/s.js ./src2/s/s/s/s/s/s/s/s.js ./src2/s/s/s/s/s/s/s/s/s.js ./src2/s/s/s/s/s/s/s/s/s/s.js ./src2/s/s/s/s/s/s/s/s/s/s/s.js ./src2/t/t.js ./src2/t/t/t.js ./src2/t/t/t/t.js ./src2/t/t/t/t/t.js ./src2/t/t/t/t/t/t.js ./src2/t/t/t/t/t/t/t.js ./src2/t/t/t/t/t/t/t/t.js ./src2/t/t/t/t/t/t/t/t/t.js ./src2/t/t/t/t/t/t/t/t/t/t.js ./src2/t/t/t/t/t/t/t/t/t/t/t.js ./src2/u/u.js ./src2/u/u/u.js ./src2/u/u/u/u.js ./src2/u/u/u/u/u.js ./src2/u/u/u/u/u/u.js ./src2/u/u/u/u/u/u/u.js ./src2/u/u/u/u/u/u/u/u.js ./src2/u/u/u/u/u/u/u/u/u.js ./src2/u/u/u/u/u/u/u/u/u/u.js ./src2/u/u/u/u/u/u/u/u/u/u/u.js ./src2/v/v.js ./src2/v/v/v.js ./src2/v/v/v/v.js ./src2/v/v/v/v/v.js ./src2/v/v/v/v/v/v.js ./src2/v/v/v/v/v/v/v.js ./src2/v/v/v/v/v/v/v/v.js ./src2/v/v/v/v/v/v/v/v/v.js ./src2/v/v/v/v/v/v/v/v/v/v.js ./src2/v/v/v/v/v/v/v/v/v/v/v.js ./src2/w/w.js ./src2/w/w/w.js ./src2/w/w/w/w.js ./src2/w/w/w/w/w.js ./src2/w/w/w/w/w/w.js ./src2/w/w/w/w/w/w/w.js ./src2/w/w/w/w/w/w/w/w.js ./src2/w/w/w/w/w/w/w/w/w.js ./src2/w/w/w/w/w/w/w/w/w/w.js ./src2/w/w/w/w/w/w/w/w/w/w/w.js ./src2/x/x.js ./src2/x/x/x.js ./src2/x/x/x/x.js ./src2/x/x/x/x/x.js ./src2/x/x/x/x/x/x.js ./src2/x/x/x/x/x/x/x.js ./src2/x/x/x/x/x/x/x/x.js ./src2/x/x/x/x/x/x/x/x/x.js ./src2/x/x/x/x/x/x/x/x/x/x.js ./src2/x/x/x/x/x/x/x/x/x/x/x.js ./src2/y/y.js ./src2/y/y/y.js ./src2/y/y/y/y.js ./src2/y/y/y/y/y.js ./src2/y/y/y/y/y/y.js ./src2/y/y/y/y/y/y/y.js ./src2/y/y/y/y/y/y/y/y.js ./src2/y/y/y/y/y/y/y/y/y.js ./src2/y/y/y/y/y/y/y/y/y/y.js ./src2/y/y/y/y/y/y/y/y/y/y/y.js ./src2/z/z.js ./src2/z/z/z.js ./src2/z/z/z/z.js ./src2/z/z/z/z/z.js ./src2/z/z/z/z/z/z.js ./src2/z/z/z/z/z/z/z.js ./src2/z/z/z/z/z/z/z/z.js ./src2/z/z/z/z/z/z/z/z/z.js ./src2/z/z/z/z/z/z/z/z/z/z.js ./src2/z/z/z/z/z/z/z/z/z/z/z.js"

### CODE REVIEW

**Comment by valscion** [comment]
Hmm, but wouldn't this ignore entirely legit uses of the multi entry modules, too? If someone has 

```js
module.exports = {
  entry: {
    main: [ './file1.js', './file2.js' ]
  }
  // ...
}
```

...wouldn't this ignore this, too?

**Comment by bsuh** [comment]
The stats would contain 3 modules with names "multi ./file1.js ./file2.js", "./file1.js", and "./file2.js". The patch only ignores the names beginning with multi and the individual modules forming the multi are still processed.

**Comment by valscion** [comment]
Oh OK. I'll have to check that out. Thanks for the details!

**Comment by th0r** [comment]
I don't think we should ignore it because this module is still a part of your bundle and takes some space in it.

**Comment by bsuh** [comment]
@th0r How do you propose the sizes be generated? What would be the stat size? The parsedSrc ends up being the entire bundle itself. So it overwhelms the parsed and gzip size graphs. The webpack stats output does have a small size for the multi module, maybe for the overhead of wrapping the individual modules. But how would we get the src for just that overhead?

**Comment by th0r** [comment]
@bsuh The thing is this `multi` module is a normal module - it has separate `id` and some generated sources.

I've created a reproduction with this config:
```js
module.exports = {
  context: `${__dirname}/src`,
  entry: {
    main: [
      './a.js',
      './b.js',
      './c.js'
    ]
  },
  output: {
    filename: './output/bundle.js'
  },
  plugins: [
    new webpack.NamedModulesPlugin(),
    new BundleAnalyzerPlugin({
      generateStatsFile: true
    })
  ]
};
```

Generated stats file contains  this `multi` module:
```json
{
      "id": 0,
      "identifier": "multi ./a.js ./b.js ./c.js",
      "name": "multi ./a.js ./b.js ./c.js",
      "index": 0,
      "index2": 3,
      "size": 52,
      "cacheable": true,
      "built": true,
      "optional": false,
      "prefetched": false,
      "chunks": [
        0
      ],
      "assets": [],
      "issuer": null,
      "issuerId": null,
      "issuerName": null,
      "failed": false,
      "errors": 0,
      "warnings": 0,
      "reasons": [],
      "usedExports": true,
      "providedExports": null,
      "optimizationBailout": [],
      "depth": 0
    }
```

And it's source can be found in the generated bundle:
```js
(function(module, exports, __webpack_require__) {
__webpack_require__("./a.js");
__webpack_require__("./b.js");
module.exports = __webpack_require__("./c.js");
})
```

So as you can see it's a normal module that takes space in resulting bundle and can be parsed so we can get it's real size.

The only thing we should do is treat these `multi` modules differently and not generate deeply nested tree for them.

**Pull request closed without merging**
